### PR TITLE
Add explicit dependancy

### PR DESCRIPTION
**Pull request by RealOrangeOne**
When trying to require `circleci` module, the require fails because the module depends on `url`, which isnt explicitly defined in the `package.json`.

If I manually install `url`, then this fixes the problem. Therefore adding `url` to the dependencies should fix the problem. I have checked and it is used in this module, but not explicitly defined.

### CODE REVIEW

**Comment by jpstevens** [comment]
Hi @RealOrangeOne which version of Node are you using?

`url` is part of the Node standard lib, so there should be no need to install it: https://nodejs.org/api/url.html

**Comment by RealOrangeOne** [comment]
I'm using `v4.2.6`. When was the `url` library added to nodejs?.

**Comment by RealOrangeOne** [comment]
@jpstevens I think the problem is that i'm trying to use it in react native, which isnt bundling it correctly. Although adding url to the package does fix this problem, presumably because it's using purejs not nodejs

**Comment by jpstevens** [comment]
@RealOrangeOne I don't know when `url` was added to node, but it's been in there since at least (v0.4)[https://nodejs.org/docs/v0.4.12/api/url.html]

**Comment by RealOrangeOne** [comment]
Well, its definately there in `4.2.6`. Unfortunately I think the problem is the fact i'm trying to run it on the client, which doesnt have access to the nodejs libraries libraries like `url`. Adding this library would mean that this library is usable on the client as well as on nodejs?

**Comment by jpstevens** [comment]
If you install `url` in your ReactNative project, does it work then?

**Comment by RealOrangeOne** [comment]
Unfortunately not, for some reason I have to install a load of modules. Current total of extras is 4, gave up after that. Clearly a small rewrite would be in order to make this work on the client-size. :hankey:

**Pull request closed without merging**
